"git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
runtime! debian.vim

if has("syntax")
  syntax on
endif

set nocompatible               " be iMproved
filetype off                   " required!

let mapleader=","

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required! 
Bundle 'gmarik/vundle'
" My Bundles here:
"
" original repos on github
Bundle 'scrooloose/nerdtree.git'
Bundle 'nathanaelkane/vim-indent-guides.git'
" vim-scripts repos
Bundle 'taglist.vim'
Bundle 'AutoComplPop'
"sudo apt-get install exuberant-ctags
" non github repos
"Bundle 'git://git.wincent.com/command-t.git'

filetype plugin indent on     " required!

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

set encoding=utf-8
set termencoding=utf-8
set fileencodings=utf-8,gbk

set ts=4
set expandtab
set autoindent
let Tlist_Use_Right_Window=1
let g:indent_guides_guide_size=1
:nnoremap <F8> :exe 'NERDTreeToggle'<CR>
