"git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
runtime! debian.vim

set encoding=utf-8
set termencoding=utf-8
set fileencodings=utf-8,gbk
set nu

if has("syntax")
  syntax on
endif

if $COLORTERM == 'gnome-terminal'
    set t_Co=256
endif

set nocompatible               " be iMproved
filetype off                   " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required! 
Bundle 'gmarik/vundle'
" My Bundles here:
"
" original repos on github
Bundle 'scrooloose/nerdtree.git'
Bundle 'nathanaelkane/vim-indent-guides.git'
Bundle 'Lokaltog/vim-powerline.git'
"Bundle 'wincent/Command-T.git'
" vim-scripts repos
Bundle 'majutsushi/tagbar.git'
Bundle 'AutoComplPop'
Bundle 'airblade/vim-gitgutter'
" non github repos
"Bundle 'git://git.wincent.com/command-t.git'

filetype plugin indent on     " required!

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

"powerline{
set guifont=PowerlineSymbols\ for\ Powerline
set nocompatible
let g:Powerline_symbols = 'fancy'
"}

set ts=4
set sw=4
set sts=4

set hlsearch
set expandtab
set autoindent
let Tlist_Use_Right_Window=1
let g:indent_guides_guide_size=1
:nnoremap <F8> :exe 'NERDTreeToggle'<CR>
"colo distinguished
syntax enable
set background=dark
colorscheme default
let g:solarized_termcolors=256

set pastetoggle=<F9>
